### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by jpasholk** [abhn/Soot-Spirits#3]
Can you add pagination to this theme?

Thank you.

**Comment by abhn** [comment]
Yeah sure, I'll add it.

**Comment by jpasholk** [comment]
Did you ever get around to this? If not I may take a stab at it. :)

**Comment by abhn** [comment]
Hey, @jpasholk! Thank you for the kind followup. That would be wonderful. Please do it.

Sorry, I didn't get it done (even after a year). :( Need to learn how to take better care of my projects. Haha.

Thanks again and cheers!

**Comment by jpasholk** [comment]
Okay, I'm almost done! I'll submit a pull request and link to a Netlify build so you can preview it.

I've also fixed some other stuff that I felt was needed. Feel free to include or exclude any of that if you'd like. :)
