### ISSUE TITLE
Markdown Highlighting

### ISSUE THREAD

**Issue by wagonhelm** [abhn/Soot-Spirits#6]
Really love this theme but I cannot get any markdown styling or highlighting to work.  I.e. headings and code syntax.  Could you possibly point me in the right direction to get this working, or possibly it is working and if how could I change it to standard github md styling?

Cheers,
Justin
[wagonhelm.github.io](http://wagonhelm.github.io)

**Comment by abhn** [comment]
Thanks @wagonhelm for dropping by,

I believe you're talking about code highlighting for markdown. I'll see if I can get it to work on my end, and push a fix. Will update you on the same here.

Regards,
Abhishek

**Comment by jpasholk** [comment]
@wagonhelm I fixed this in my [fork](https://github.com/jpasholk/Soot-Spirits). :)
